# Generated by Django 6.0.4 on 2026-06-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_orderitem_quantity_alter_order_status_cartitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('artifact_approved', 'Artifact approved'), ('artifact_rejected', 'Artifact rejected'), ('artifact_deleted', 'Artifact deleted'), ('gallery_deleted', 'Gallery deleted'), ('user_role_changed', 'User role changed'), ('user_disabled', 'User disabled'), ('user_enabled', 'User enabled')], max_length=40)),
                ('target_model', models.CharField(max_length=40)),
                ('target_id', models.PositiveIntegerField()),
                ('target_label', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
