# Generated by Django 6.0.4 on 2026-06-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_conversation_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artifact',
            name='materials',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
