# Generated by Django 6.0.4 on 2026-06-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_artifact_dimensions_artifact_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artifacts/images/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='marketplace.artifact')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
