# Generated by Django 6.0.4 on 2026-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_artifactimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action_type',
            field=models.CharField(choices=[('artifact_approved', 'Artifact approved'), ('artifact_rejected', 'Artifact rejected'), ('artifact_deleted', 'Artifact deleted'), ('gallery_deleted', 'Gallery deleted'), ('user_role_changed', 'User role changed'), ('user_disabled', 'User disabled'), ('user_enabled', 'User enabled'), ('user_suspended', 'User suspended'), ('user_unsuspended', 'User unsuspended'), ('seller_verified', 'Seller verified'), ('seller_unverified', 'Seller unverified')], max_length=40),
        ),
    ]
