import os

FILE = r'c:\Users\boura\ouissal\pfe-antique-marketplace-1\docs\generate_report.py'

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    # Cover
    '"Filiere : Developpement Informatique"': '"Filière : Développement Informatique"',
    '"Rapport de Projet de Fin d\'Etudes"': '"Rapport de Projet de Fin d\'Études"',
    '"Marketplace premium d\'antiquites et d\'objets de collection"': '"Marketplace premium d\'antiquités et d\'objets de collection"',
    '"Etablissement"': '"Établissement"',
    '"Filiere"': '"Filière"',
    '"Developpement Informatique"': '"Développement Informatique"',
    '"Realise par"': '"Réalisé par"',
    '"Encadre par"': '"Encadré par"',
    '"Annee universitaire"': '"Année universitaire"',
    
    # Sections
    '"Remerciements"': '"Remerciements"',
    '"Resume"': '"Résumé"',
    '"Resume / Abstract"': '"Résumé / Abstract"',
    '"Table des matieres"': '"Table des matières"',
    '"Liste des figures"': '"Liste des figures"',
    '"Liste des tableaux"': '"Liste des tableaux"',
    '"Liste des abreviations"': '"Liste des abréviations"',
    '"Introduction generale"': '"Introduction générale"',
    
    # Text in Remerciements
    "a exprimer": "à exprimer",
    "contribue": "contribué",
    "a la realisation": "à la réalisation",
    "d'etudes": "d'études",
    "tout d'abord": "tout d'abord",
    "avises": "avisés",
    "disponibilite": "disponibilité",
    "ete determinantes": "été déterminantes",
    "a structurer": "à structurer",
    "a clarifier": "à clarifier",
    "a maintenir": "à maintenir",
    "egalement": "également",
    "a l'ensemble": "à l'ensemble",
    "pedagogique": "pédagogique",
    "dispensee": "dispensée",
    "a notre disposition": "à notre disposition",
    "académiques": "académiques",
    "m'ont permis": "m'ont permis",
    "a bien": "à bien",
    
    # Text in Resume
    "fin d'etudes": "fin d'études",
    "realisation": "réalisation",
    "dediee": "dédiée",
    "a la vente": "à la vente",
    "decouverte": "découverte",
    "a ete pense": "a été pensé",
    "repondant": "répondant",
    "developpe": "développé",
    "a forte": "à forte",
    "identite": "identité",
    "inspiree": "inspirée",
    "adaptee a chaque role": "adaptée à chaque rôle",
    "integre": "intègre",
    "roles": "rôles",
    "specifiques": "spécifiques",
    "detaillee": "détaillée",
    "Mots-cles": "Mots-clés",
    
    # Body text replaces
    "a pour but": "a pour but",
    "Caracteristiques": "Caractéristiques",
    "Fonctionnalites": "Fonctionnalités",
    "Sécurité": "Sécurité",
    "Authentification": "Authentification",
    "Creation": "Création",
    "Modification": "Modification",
    "Supression": "Suppression",
    "Operation": "Opération",
    "a jour": "à jour",
    "necessaires": "nécessaires",
    "specifiques": "spécifiques",
    "Developpement": "Développement",
    "Creation": "Création",
    "Realisation": "Réalisation",
    "Integration": "Intégration",
    "Depoiement": "Déploiement",
    "probleme": "problème",
    "systeme": "système",
    "Systeme": "Système",
    "general": "général",
    "Generale": "Générale",
    "generale": "générale",
    "modelisation": "modélisation",
    "Modelisation": "Modélisation",
    "donnees": "données",
    "Donnees": "Données",
    "Entite": "Entité",
    "Architecture generale": "Architecture générale",
    "differents": "différents",
    "differentes": "différentes",
    "etape": "étape",
    "etapes": "étapes",
    "methode": "méthode",
    "methodologie": "méthodologie",
    "tache": "tâche",
    "taches": "tâches",
    "cout": "coût",
    "couts": "coûts",
    "Securite": "Sécurité",
    "controle": "contrôle",
    "Controle": "Contrôle",
    "acces": "accès",
    "Acces": "Accès",
    "base sur": "basé sur",
    "Base sur": "Basé sur",
    "Regles": "Règles",
    "gestion": "gestion",
    "Sequence": "Séquence",
    "sequence": "séquence",
    "Utilisateurs": "Utilisateurs",
    "utilisateurs": "utilisateurs",
    "Probleme": "Problème",
    "problematique": "problématique",
    "Problematique": "Problématique",
    "valeur ajoutee": "valeur ajoutée",
    "Valeur ajoutee": "Valeur ajoutée",
    "perimetre": "périmètre",
    "Perimetre": "Périmètre",
    "fonctionnel": "fonctionnel",
    "Besoins fonctionnels": "Besoins fonctionnels",
    "besoins non fonctionnels": "besoins non fonctionnels",
    "Diagramme des cas d'utilisation": "Diagramme des cas d'utilisation",
    "Technologies utilisees": "Technologies utilisées",
    "utiliser": "utiliser",
    "utilise": "utilisé",
    "utilisee": "utilisée",
    "utilises": "utilisés",
    "utilisees": "utilisées",
    "Realisation de la solution": "Réalisation de la solution",
    "Interfaces et fonctionnalites": "Interfaces et fonctionnalités",
    "developpees": "développées",
    "Page d'accueil publique": "Page d'accueil publique",
    "Tableau de bord administrateur": "Tableau de bord administrateur",
    "Conlusion generale": "Conclusion générale",
    "Conclusion generale": "Conclusion générale",
    "perspectives": "perspectives",
    
    # Specifically targeting strings in big_title and chapter_title
    'pdf.big_title("Remerciements")': 'pdf.add_page()\n    pdf.big_title("Remerciements")',
    'pdf.big_title("Resume")': 'pdf.add_page()\n    pdf.big_title("Résumé")',
    'pdf.big_title("Abstract")': 'pdf.add_page()\n    pdf.big_title("Abstract")',
    'pdf.big_title("Table des matieres"': 'pdf.add_page()\n    pdf.big_title("Table des matières"',
    'pdf.big_title("Liste des figures"': 'pdf.add_page()\n    pdf.big_title("Liste des figures"',
    'pdf.big_title("Liste des tableaux"': 'pdf.add_page()\n    pdf.big_title("Liste des tableaux"',
    'pdf.big_title("Liste des abreviations"': 'pdf.add_page()\n    pdf.big_title("Liste des abréviations"',
    'pdf.big_title("Introduction generale")': 'pdf.add_page()\n    pdf.start_numbering = True\n    pdf.page_offset = pdf.page_no() - 1\n    pdf.big_title("Introduction générale")',
    
    'pdf.chapter_separator(1, "Presentation generale du projet")': 'pdf.chapter_separator(1, "Présentation générale du projet")',
    'pdf.chapter_separator(2, "Analyse des besoins")': 'pdf.chapter_separator(2, "Analyse des besoins")',
    'pdf.chapter_separator(3, "Conception")': 'pdf.chapter_separator(3, "Conception")',
    'pdf.chapter_separator(4, "Realisation de la solution")': 'pdf.chapter_separator(4, "Réalisation de la solution")',
    'pdf.big_title("Conclusion generale")': 'pdf.big_title("Conclusion générale")',
}

for old, new in replacements.items():
    content = content.replace(old, new)

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print("Text replaced successfully.")
